import React, { useState } from 'react';
import { DataGrid, type DataGridRow } from '../DataGrid';
import { Eye, EyeOff } from 'lucide-react';

interface HeadersParamsProps {
    rows: DataGridRow[];
    onChange: (rows: DataGridRow[]) => void;
}

const autoGeneratedHeaders: DataGridRow[] = [
    { id: 'host-auto', enabled: true, key: 'Host', value: '<calculated when request is sent>', description: 'Auto-generated', readonly: true },
    { id: 'user-agent-auto', enabled: true, key: 'User-Agent', value: 'ced-client/1.0', description: 'Auto-generated', readonly: true },
    { id: 'accept-auto', enabled: true, key: 'Accept', value: '*/*', description: 'Auto-generated', readonly: true },
    { id: 'content-length-auto', enabled: true, key: 'Content-Length', value: '<calculated when request is sent>', description: 'Auto-generated', readonly: true },
];

export const HeadersTab: React.FC<HeadersParamsProps> = ({ rows, onChange }) => {
    const [showAutoGenerated, setShowAutoGenerated] = useState(false);

    const displayRows = showAutoGenerated ? [...rows.slice(0, -1), ...autoGeneratedHeaders, rows[rows.length - 1]] : rows;

    const handleGridChange = (newRows: DataGridRow[]) => {
        // Filter out auto-generated rows when saving back
        onChange(newRows.filter(r => !r.readonly));
    };

    const applyPreset = (preset: 'json' | 'form') => {
        // Lấy danh sách hiện tại, loại bỏ dòng trống
        const newRows = [...rows.filter(r => r.key !== '' || r.value !== '')];

        const addOrUpdateHeader = (key: string, value: string) => {
            const index = newRows.findIndex(r => r.key.toLowerCase() === key.toLowerCase());
            if (index >= 0) {
                newRows[index] = { ...newRows[index], value, enabled: true };
            } else {
                newRows.push({
                    id: Math.random().toString(36).substring(7),
                    enabled: true,
                    key,
                    value,
                    description: ''
                });
            }
        };

        if (preset === 'json') {
            addOrUpdateHeader('Content-Type', 'application/json');
            addOrUpdateHeader('Accept', 'application/json');
        } else if (preset === 'form') {
            addOrUpdateHeader('Content-Type', 'application/x-www-form-urlencoded');
        }

        onChange(newRows);
    };

    return (
        <div className="flex flex-col h-full bg-white">
            <div className="flex px-4 py-2 border-b border-slate-200 justify-between items-center text-xs">
                <span className="text-slate-500 font-medium">Headers</span>
                <div className="flex gap-4">
                    <div className="flex items-center gap-2">
                        <span className="text-slate-400">Presets:</span>
                        <button onClick={() => applyPreset('json')} className="hover:text-orange-500 text-slate-600 font-medium transition-colors">JSON</button>
                        <button onClick={() => applyPreset('form')} className="hover:text-orange-500 text-slate-600 font-medium transition-colors">Form-Data</button>
                    </div>

                    <div className="w-px h-4 bg-slate-300"></div>

                    <button
                        onClick={() => setShowAutoGenerated(!showAutoGenerated)}
                        className="flex items-center gap-1 text-slate-500 hover:text-slate-800 transition-colors bg-slate-100 hover:bg-slate-200 px-2 py-1 rounded"
                    >
                        {showAutoGenerated ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                        {showAutoGenerated ? 'Hide auto-generated' : '7 hidden'}
                    </button>
                </div>
            </div>

            <div className="flex-1 overflow-hidden">
                <DataGrid rows={displayRows} onChange={handleGridChange} />
            </div>
        </div>
    );
};
