import React, { useState } from 'react';
import { DataGrid, type DataGridRow } from '../DataGrid';
import { Eye, EyeOff } from 'lucide-react';

interface HeadersParamsProps {
    rows: DataGridRow[];
    onChange: (rows: DataGridRow[]) => void;
}

const autoGeneratedHeaders: DataGridRow[] = [
    { id: 'host-auto', enabled: true, key: 'Host', value: '<calculated when request is sent>', description: 'Auto-generated', readonly: true, system: true },
    { id: 'user-agent-auto', enabled: true, key: 'User-Agent', value: 'ced-client/1.0', description: 'Auto-generated', readonly: false, system: true },
    { id: 'accept-auto', enabled: true, key: 'Accept', value: '*/*', description: 'Auto-generated', readonly: true, system: true },
    { id: 'content-length-auto', enabled: true, key: 'Content-Length', value: '<calculated when request is sent>', description: 'Auto-generated', readonly: true, system: true },
];

export const HeadersTab: React.FC<HeadersParamsProps> = ({ rows, onChange }) => {
    const [showAutoGenerated, setShowAutoGenerated] = useState(false);

    const displayRows = showAutoGenerated
        ? [...rows.slice(0, -1), ...autoGeneratedHeaders.filter(ah => !rows.some(r => r.id === ah.id)), rows[rows.length - 1]]
        : rows;

    const handleGridChange = (newRows: DataGridRow[]) => {
        // Filter out unmodified system rows, and deduplicate to fix any corrupted state
        const seen = new Set<string>();
        onChange(newRows.filter(r => {
            if (seen.has(r.id)) return false;
            seen.add(r.id);

            if (r.system) {
                const defaultAuto = autoGeneratedHeaders.find(ah => ah.id === r.id);
                // If it exists and hasn't been modified at all, don't persist it. Let displayRows inject it.
                if (defaultAuto && r.enabled === defaultAuto.enabled && r.value === defaultAuto.value && r.key === defaultAuto.key) {
                    return false;
                }
            }

            return !r.readonly;
        }));
    };

    const applyPreset = (preset: 'json' | 'form') => {
        // Remove existing Content-Type and Accept to avoid duplicates
        let newRows = rows.filter(r => {
            const key = r.key.toLowerCase();
            if (preset === 'json') {
                return key !== 'content-type' && key !== 'accept' && r.key !== '';
            }
            if (preset === 'form') {
                return key !== 'content-type' && r.key !== '';
            }
            return r.key !== '';
        });

        if (preset === 'json') {
            newRows.push({
                id: Math.random().toString(36).substring(7),
                enabled: true,
                key: 'Content-Type',
                value: 'application/json',
                description: ''
            });
            newRows.push({
                id: Math.random().toString(36).substring(7),
                enabled: true,
                key: 'Accept',
                value: 'application/json',
                description: ''
            });
        } else if (preset === 'form') {
            newRows.push({
                id: Math.random().toString(36).substring(7),
                enabled: true,
                key: 'Content-Type',
                value: 'application/x-www-form-urlencoded',
                description: ''
            });
        }

        // Add back an empty row at the end if not already present
        if (newRows.length === 0 || newRows[newRows.length - 1].key !== '') {
            newRows.push({
                id: Math.random().toString(36).substring(7),
                enabled: true,
                key: '',
                value: '',
                description: ''
            });
        }

        onChange(newRows);
    };

    return (
        <div className="flex flex-col h-full bg-white">
            <div className="flex px-4 py-2 border-b border-slate-200 justify-between items-center text-xs">
                <span className="text-slate-500 font-medium">Headers</span>
                <div className="flex gap-4">
                    <div className="flex items-center gap-2">
                        <span className="text-slate-400">Presets:</span>
                        <button onClick={() => applyPreset('json')} className="hover:text-orange-500 text-slate-600 font-medium transition-colors">JSON</button>
                        <button onClick={() => applyPreset('form')} className="hover:text-orange-500 text-slate-600 font-medium transition-colors">Form-Data</button>
                    </div>

                    <div className="w-px h-4 bg-slate-300"></div>

                    <button
                        onClick={() => setShowAutoGenerated(!showAutoGenerated)}
                        className="flex items-center gap-1 text-slate-500 hover:text-slate-800 transition-colors bg-slate-100 hover:bg-slate-200 px-2 py-1 rounded"
                    >
                        {showAutoGenerated ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                        {showAutoGenerated ? 'Hide auto-generated' : '7 hidden'}
                    </button>
                </div>
            </div>

            <div className="flex-1 overflow-hidden">
                <DataGrid rows={displayRows} onChange={handleGridChange} />
            </div>
        </div>
    );
};
